---
abstract: 'Creates calendars in SVG format which can be printed'
author:
  - 'Ivan Wills <ivan.wills@gmail.com>'
build_requires:
  Test::More: '0'
  Test::Warnings: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SVG-Calendar
provides:
  SVG::Calendar:
    file: lib/SVG/Calendar.pm
    version: v0.3.5
recommends:
  Astro::Coord::ECI::Moon: '0.044'
  Astro::MoonPhase: '0.6'
  Pod::Coverage: '0'
  Test::Kwalitee: '0'
  Test::Perl::Critic: '0'
  Test::Spelling: '0'
requires:
  Clone: '0.17'
  Config::Std: '0'
  DateTime::Format::Strptime: '0'
  Image::ExifTool: '7.0'
  Math::Trig: '1.15'
  Readonly: '1.03'
  SVG: '2.33'
  Scalar::Util: '0'
  Template: '2.14'
  Template::Provider::FromDATA: '0.08'
  perl: '5.006'
  version: '0.74'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=SVG-Calendar
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ivanwills/SVG-Calendar.git
version: v0.3.5
